[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; frame-ancestors 'none'; form-action 'self'; base-uri 'self'; connect-src 'self' https://3oopqm4jjc5sb4yrc2wznkzu6i0pklqv.lambda-url.eu-north-1.on.aws/"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    

