[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = default-src 'none'
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
